# Generated by Django 6.0.3 on 2026-04-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('displays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_logs', to='content.ad')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_logs', to='displays.screen')),
            ],
        ),
    ]
