# Generated by Django 6.0.3 on 2026-04-04 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('displays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_file', models.FileField(upload_to='ads/')),
                ('duration', models.PositiveIntegerField(default=10, help_text='Duration in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='content.ad')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_assignments', to='displays.screen')),
            ],
            options={
                'ordering': ['display_order', 'start_date'],
            },
        ),
    ]
